# Generated by Django 5.0 on 2023-12-19 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_blocks', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ListProfessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_professions', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_birth', models.DateField(blank=True)),
                ('email_persons', models.EmailField(max_length=254)),
                ('slack', models.CharField(max_length=20)),
                ('discord', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_positions', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EducationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_education_block', models.CharField(max_length=20)),
                ('kod_education_block', models.IntegerField()),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField()),
                ('date_closing', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Координатор', to='unit_programming.persons')),
            ],
        ),
        migrations.AddField(
            model_name='persons',
            name='id_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit_programming.positions'),
        ),
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_profession', models.CharField(max_length=200)),
                ('kod_profession', models.IntegerField()),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField()),
                ('date_closing', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Координатор+', to='unit_programming.persons')),
                ('id_education_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Блок обучения+', to='unit_programming.educationblock')),
                ('id_lead_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ВКН', to='unit_programming.persons')),
            ],
        ),
        migrations.AddField(
            model_name='educationblock',
            name='id_profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Профессиb', to='unit_programming.professions'),
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_unit', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('id_profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Профессия', to='unit_programming.professions')),
            ],
        ),
        migrations.AddField(
            model_name='professions',
            name='id_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit_programming.units'),
        ),
    ]
